export const ACHIEVEMENTS = {
  first_lesson: {
    id: 'first_lesson',
    name: 'Первый шаг',
    description: 'Пройди свой первый урок',
    icon: '🎓',
    points: 10
  },
  three_days_streak: {
    id: 'three_days_streak',
    name: 'Упорный',
    description: 'Занимайся 3 дня подряд',
    icon: '🔥',
    points: 25
  },
  week_streak: {
    id: 'week_streak',
    name: 'Неделя успеха',
    description: 'Занимайся 7 дней подряд',
    icon: '⭐',
    points: 50
  },
  month_streak: {
    id: 'month_streak',
    name: 'Месяц силы',
    description: 'Занимайся 30 дней подряд',
    icon: '💎',
    points: 200
  },
  word_master_50: {
    id: 'word_master_50',
    name: 'Словарный запас',
    description: 'Изучи 50 слов',
    icon: '📚',
    points: 30
  },
  word_master_100: {
    id: 'word_master_100',
    name: 'Полиглот',
    description: 'Изучи 100 слов',
    icon: '🧠',
    points: 75
  },
  perfect_score: {
    id: 'perfect_score',
    name: 'Идеально!',
    description: 'Получи 100% на уроке',
    icon: '🌟',
    points: 15
  },
  five_perfect: {
    id: 'five_perfect',
    name: 'Мастер',
    description: 'Получи 100% на 5 уроках',
    icon: '👑',
    points: 100
  },
  early_bird: {
    id: 'early_bird',
    name: 'Ранняя птичка',
    description: 'Пройди урок до 9 утра',
    icon: '🌅',
    points: 20
  },
  night_owl: {
    id: 'night_owl',
    name: 'Сова',
    description: 'Пройди урок после 23:00',
    icon: '🦉',
    points: 20
  },
  speed_demon: {
    id: 'speed_demon',
    name: 'Скоростной режим',
    description: 'Пройди урок за 5 минут',
    icon: '⚡',
    points: 25
  },
  level_up_a1: {
    id: 'level_up_a1',
    name: 'Переход на A1',
    description: 'Достигни уровня A1',
    icon: '🎯',
    points: 50
  },
  level_up_a2: {
    id: 'level_up_a2',
    name: 'Переход на A2',
    description: 'Достигни уровня A2',
    icon: '🏆',
    points: 100
  },
  // STREAKS
  streak_14: { id: 'streak_14', name: 'Две недели', description: 'Занимайся 14 дней подряд', icon: '🔥', points: 75 },
  streak_30: { id: 'streak_30', name: 'Месяц', description: 'Занимайся 30 дней подряд', icon: '📅', points: 150 },
  streak_60: { id: 'streak_60', name: 'Два месяца', description: 'Занимайся 60 дней подряд', icon: '🗓️', points: 300 },
  streak_90: { id: 'streak_90', name: 'Сезон', description: 'Занимайся 90 дней подряд', icon: '🍂', points: 450 },
  streak_100: { id: 'streak_100', name: 'Сотня', description: 'Занимайся 100 дней подряд', icon: '💯', points: 500 },
  streak_150: { id: 'streak_150', name: 'Полгода почти', description: 'Занимайся 150 дней подряд', icon: '🌓', points: 750 },
  streak_180: { id: 'streak_180', name: 'Полгода', description: 'Занимайся 180 дней подряд', icon: '🌗', points: 900 },
  streak_250: { id: 'streak_250', name: 'Стойкий', description: 'Занимайся 250 дней подряд', icon: '🛡️', points: 1250 },
  streak_365: { id: 'streak_365', name: 'Легенда', description: 'Занимайся 365 дней подряд', icon: '👑', points: 2000 },

  // LESSONS
  lessons_5: { id: 'lessons_5', name: 'Разминка', description: 'Пройди 5 уроков', icon: '🐣', points: 25 },
  lessons_10: { id: 'lessons_10', name: 'Начало пути', description: 'Пройди 10 уроков', icon: '🚶', points: 50 },
  lessons_25: { id: 'lessons_25', name: 'Студент', description: 'Пройди 25 уроков', icon: '🎒', points: 125 },
  lessons_50: { id: 'lessons_50', name: 'Ученик', description: 'Пройди 50 уроков', icon: '📖', points: 250 },
  lessons_75: { id: 'lessons_75', name: 'Знаток', description: 'Пройди 75 уроков', icon: '🧐', points: 375 },
  lessons_100: { id: 'lessons_100', name: 'Профи', description: 'Пройди 100 уроков', icon: '🎓', points: 500 },
  lessons_150: { id: 'lessons_150', name: 'Магистр', description: 'Пройди 150 уроков', icon: '🧙‍♂️', points: 750 },
  lessons_200: { id: 'lessons_200', name: 'Гранд-мастер', description: 'Пройди 200 уроков', icon: '🧘', points: 1000 },
  lessons_300: { id: 'lessons_300', name: 'Мудрец', description: 'Пройди 300 уроков', icon: '👴', points: 1500 },
  lessons_500: { id: 'lessons_500', name: 'Бессмертный', description: 'Пройди 500 уроков', icon: '🧛', points: 2500 },

  // WORDS
  words_10: { id: 'words_10', name: 'Первые слова', description: 'Изучи 10 слов', icon: '🅰️', points: 10 },
  words_25: { id: 'words_25', name: 'Словарик', description: 'Изучи 25 слов', icon: '📒', points: 25 },
  words_250: { id: 'words_250', name: 'Лексикон', description: 'Изучи 250 слов', icon: '📚', points: 250 },
  words_500: { id: 'words_500', name: 'Эрудит', description: 'Изучи 500 слов', icon: '🤓', points: 500 },
  words_1000: { id: 'words_1000', name: 'Словарь', description: 'Изучи 1000 слов', icon: '📖', points: 1000 },
  words_2000: { id: 'words_2000', name: 'Энциклопедия', description: 'Изучи 2000 слов', icon: '🏛️', points: 2000 },
  words_5000: { id: 'words_5000', name: 'Живой язык', description: 'Изучи 5000 слов', icon: '🗣️', points: 5000 },

  // XP
  xp_100: { id: 'xp_100', name: 'Новичок XP', description: 'Набери 100 XP', icon: '🥉', points: 10 },
  xp_500: { id: 'xp_500', name: 'Любитель XP', description: 'Набери 500 XP', icon: '🥈', points: 50 },
  xp_1000: { id: 'xp_1000', name: 'Опытный XP', description: 'Набери 1000 XP', icon: '🥇', points: 100 },
  xp_5000: { id: 'xp_5000', name: 'Мастер XP', description: 'Набери 5000 XP', icon: '🎖️', points: 500 },
  xp_10000: { id: 'xp_10000', name: 'Легенда XP', description: 'Набери 10000 XP', icon: '🏵️', points: 1000 },
  xp_50000: { id: 'xp_50000', name: 'Бог XP', description: 'Набери 50000 XP', icon: '🛐', points: 5000 },

  // PERFECT
  perfect_3: { id: 'perfect_3', name: 'Тройной успех', description: 'Идеально пройди 3 урока', icon: '✨', points: 50 },
  perfect_10: { id: 'perfect_10', name: 'Десятка', description: 'Идеально пройди 10 уроков', icon: '🔟', points: 150 },
  perfect_50: { id: 'perfect_50', name: 'Перфекционист', description: 'Идеально пройди 50 уроков', icon: '💎', points: 500 },

  // TIME
  weekend_warrior: { id: 'weekend_warrior', name: 'Воин выходных', description: 'Занимайся в субботу или воскресенье', icon: '🏖️', points: 30 },
  lunch_learner: { id: 'lunch_learner', name: 'Обеденный перерыв', description: 'Занимайся с 13:00 до 14:00', icon: '🍱', points: 20 },
  level_up_b1: { id: 'level_up_b1', name: 'B1', description: 'Достигни уровня B1', icon: '📈', points: 200 },
  level_up_b2: { id: 'level_up_b2', name: 'B2', description: 'Достигни уровня B2', icon: '🚀', points: 300 },
  level_up_c1: { id: 'level_up_c1', name: 'C1', description: 'Достигни уровня C1', icon: '🛸', points: 500 },

  // --- BATCH 2 ---
  // STREAKS (6)
  streak_21: { id: 'streak_21', name: 'Привычка', description: 'Занимайся 21 день подряд', icon: '🏗️', points: 100 },
  streak_45: { id: 'streak_45', name: 'Полтора месяца', description: 'Занимайся 45 дней подряд', icon: '🗓️', points: 200 },
  streak_75: { id: 'streak_75', name: '75 Дней', description: 'Занимайся 75 дней подряд', icon: '💪', points: 350 },
  streak_200: { id: 'streak_200', name: '200 Дней', description: 'Занимайся 200 дней подряд', icon: '🧗', points: 1000 },
  streak_300: { id: 'streak_300', name: 'Почти год', description: 'Занимайся 300 дней подряд', icon: '🎆', points: 1500 },
  streak_400: { id: 'streak_400', name: '400 Дней', description: 'Занимайся 400 дней подряд', icon: '🚀', points: 2500 },

  // LESSONS (14)
  lessons_15: { id: 'lessons_15', name: 'Разгон', description: 'Пройди 15 уроков', icon: '🏃', points: 35 },
  lessons_35: { id: 'lessons_35', name: 'Активный', description: 'Пройди 35 уроков', icon: '🏋️', points: 175 },
  lessons_60: { id: 'lessons_60', name: 'Продвинутый', description: 'Пройди 60 уроков', icon: '🤸', points: 300 },
  lessons_80: { id: 'lessons_80', name: 'Эксперт', description: 'Пройди 80 уроков', icon: '🥋', points: 400 },
  lessons_90: { id: 'lessons_90', name: 'Мастер обучения', description: 'Пройди 90 уроков', icon: '🧘', points: 450 },
  lessons_125: { id: 'lessons_125', name: 'Ветеран', description: 'Пройди 125 уроков', icon: '🎖️', points: 600 },
  lessons_175: { id: 'lessons_175', name: 'Гуру', description: 'Пройди 175 уроков', icon: '👳', points: 850 },
  lessons_250: { id: 'lessons_250', name: 'Профессор', description: 'Пройди 250 уроков', icon: '👨‍🏫', points: 1250 },
  lessons_400: { id: 'lessons_400', name: 'Академик', description: 'Пройди 400 уроков', icon: '🏛️', points: 2000 },
  lessons_600: { id: 'lessons_600', name: 'Титан', description: 'Пройди 600 уроков', icon: '🗿', points: 3000 },
  lessons_700: { id: 'lessons_700', name: 'Колосс', description: 'Пройди 700 уроков', icon: '🗼', points: 3500 },
  lessons_800: { id: 'lessons_800', name: 'Легендарный', description: 'Пройди 800 уроков', icon: '🐲', points: 4000 },
  lessons_900: { id: 'lessons_900', name: 'Мифический', description: 'Пройди 900 уроков', icon: '🦄', points: 4500 },
  lessons_1000: { id: 'lessons_1000', name: 'Божественный', description: 'Пройди 1000 уроков', icon: '⚡', points: 5000 },

  // WORDS (10)
  words_150: { id: 'words_150', name: 'Болтун', description: 'Изучи 150 слов', icon: '💬', points: 150 },
  words_200: { id: 'words_200', name: 'Рассказчик', description: 'Изучи 200 слов', icon: '🗣️', points: 200 },
  words_300: { id: 'words_300', name: 'Оратор', description: 'Изучи 300 слов', icon: '📢', points: 300 },
  words_400: { id: 'words_400', name: 'Лингвист', description: 'Изучи 400 слов', icon: '👅', points: 400 },
  words_600: { id: 'words_600', name: 'Толмач', description: 'Изучи 600 слов', icon: '📜', points: 600 },
  words_750: { id: 'words_750', name: 'Переводчик', description: 'Изучи 750 слов', icon: '🔤', points: 750 },
  words_800: { id: 'words_800', name: 'Словесник', description: 'Изучи 800 слов', icon: '✍️', points: 800 },
  words_900: { id: 'words_900', name: 'Писатель', description: 'Изучи 900 слов', icon: '🖋️', points: 900 },
  words_1500: { id: 'words_1500', name: 'Поэт', description: 'Изучи 1500 слов', icon: '🎭', points: 1500 },
  words_2500: { id: 'words_2500', name: 'Филолог', description: 'Изучи 2500 слов', icon: '🧐', points: 2500 },

  // XP (10)
  xp_250: { id: 'xp_250', name: 'Искатель XP', description: 'Набери 250 XP', icon: '🧭', points: 25 },
  xp_750: { id: 'xp_750', name: 'Собиратель XP', description: 'Набери 750 XP', icon: '🎒', points: 75 },
  xp_2000: { id: 'xp_2000', name: 'Воин XP', description: 'Набери 2000 XP', icon: '⚔️', points: 200 },
  xp_3000: { id: 'xp_3000', name: 'Рыцарь XP', description: 'Набери 3000 XP', icon: '🛡️', points: 300 },
  xp_4000: { id: 'xp_4000', name: 'Барон XP', description: 'Набери 4000 XP', icon: '🏰', points: 400 },
  xp_7500: { id: 'xp_7500', name: 'Герцог XP', description: 'Набери 7500 XP', icon: '👑', points: 750 },
  xp_15000: { id: 'xp_15000', name: 'Король XP', description: 'Набери 15000 XP', icon: '🤴', points: 1500 },
  xp_20000: { id: 'xp_20000', name: 'Император XP', description: 'Набери 20000 XP', icon: '👸', points: 2000 },
  xp_30000: { id: 'xp_30000', name: 'Влыдыка XP', description: 'Набери 30000 XP', icon: '🧞‍♂️', points: 3000 },
  xp_75000: { id: 'xp_75000', name: 'Абсолют XP', description: 'Набери 75000 XP', icon: '🌌', points: 7500 },

  // PERFECT (5)
  perfect_15: { id: 'perfect_15', name: '15 Идеальных', description: 'Идеально пройди 15 уроков', icon: '🎯', points: 200 },
  perfect_25: { id: 'perfect_25', name: 'Четверть сотни', description: 'Идеально пройди 25 уроков', icon: '🎱', points: 250 },
  perfect_30: { id: 'perfect_30', name: 'Тридцаточка', description: 'Идеально пройди 30 уроков', icon: '👌', points: 300 },
  perfect_40: { id: 'perfect_40', name: 'Сороковник', description: 'Идеально пройди 40 уроков', icon: '👍', points: 400 },
  perfect_75: { id: 'perfect_75', name: 'Три четверти', description: 'Идеально пройди 75 уроков', icon: '💯', points: 750 },

  // TIME (5)
  morning_coffee: { id: 'morning_coffee', name: 'Утренний кофе', description: 'Занимайся с 6:00 до 8:00', icon: '☕', points: 20 },
  lunch_break_late: { id: 'lunch_break_late', name: 'Поздний обед', description: 'Занимайся с 14:00 до 15:00', icon: '🥪', points: 20 },
  after_work: { id: 'after_work', name: 'После работы', description: 'Занимайся с 17:00 до 19:00', icon: '🌇', points: 20 },
  monday_motivation: { id: 'monday_motivation', name: 'Мотивация Пн', description: 'Занимайся в понедельник', icon: '📅', points: 30 },
  friday_fun: { id: 'friday_fun', name: 'Пятница!', description: 'Занимайся в пятницу', icon: '🎉', points: 30 },

  // --- BATCH 3: FILLER & FUN (100 New Achievements) ---

  // MICRO STREAKS (15)
  streak_2: { id: 'streak_2', name: 'Дуэт', description: 'Занимайся 2 дня подряд', icon: '✌️', points: 10 },
  streak_4: { id: 'streak_4', name: 'Квадрат', description: 'Занимайся 4 дня подряд', icon: '🍀', points: 20 },
  streak_5: { id: 'streak_5', name: 'Пятёрка', description: 'Занимайся 5 дней подряд', icon: '🖐️', points: 25 },
  streak_6: { id: 'streak_6', name: 'Шестёрка', description: 'Занимайся 6 дней подряд', icon: '🎲', points: 30 },
  streak_8: { id: 'streak_8', name: 'Восьмёрка', description: 'Занимайся 8 дней подряд', icon: '🎱', points: 40 },
  streak_9: { id: 'streak_9', name: 'Девятка', description: 'Занимайся 9 дней подряд', icon: '🕘', points: 45 },
  streak_11: { id: 'streak_11', name: 'Одиннадцать', description: 'Занимайся 11 дней подряд', icon: '⏸️', points: 55 },
  streak_12: { id: 'streak_12', name: 'Дюжина', description: 'Занимайся 12 дней подряд', icon: '🍩', points: 60 },
  streak_13: { id: 'streak_13', name: 'Чертова дюжина', description: 'Занимайся 13 дней подряд', icon: '👻', points: 65 },
  streak_15: { id: 'streak_15', name: 'Пятнашка', description: 'Занимайся 15 дней подряд', icon: '🧩', points: 75 },
  streak_16: { id: 'streak_16', name: 'Шестнадцать', description: 'Занимайся 16 дней подряд', icon: '🕯️', points: 80 },
  streak_17: { id: 'streak_17', name: 'Семнадцать', description: 'Занимайся 17 дней подряд', icon: '🦐', points: 85 },
  streak_18: { id: 'streak_18', name: 'Совершеннолетие', description: 'Занимайся 18 дней подряд', icon: '🔞', points: 90 },
  streak_19: { id: 'streak_19', name: 'Девятнадцать', description: 'Занимайся 19 дней подряд', icon: '🏐', points: 95 },
  streak_20: { id: 'streak_20', name: 'Двадцатка', description: 'Занимайся 20 дней подряд', icon: '🦢', points: 100 },

  // MICRO LESSONS (19)
  lesson_1: { id: 'lesson_1', name: 'Первый раз', description: 'Пройди 1 урок', icon: '☝️', points: 5 },
  lesson_2: { id: 'lesson_2', name: 'Второй урок', description: 'Пройди 2 урока', icon: '✌️', points: 10 },
  lesson_3: { id: 'lesson_3', name: 'Троица', description: 'Пройди 3 урока', icon: '🤟', points: 15 },
  lesson_4: { id: 'lesson_4', name: 'Квартет', description: 'Пройди 4 урока', icon: '🎻', points: 20 },
  lesson_6: { id: 'lesson_6', name: 'Шесть уроков', description: 'Пройди 6 уроков', icon: '🕕', points: 30 },
  lesson_7: { id: 'lesson_7', name: 'Семь уроков', description: 'Пройди 7 уроков', icon: '🌈', points: 35 },
  lesson_8: { id: 'lesson_8', name: 'Восемь уроков', description: 'Пройди 8 уроков', icon: '🕷️', points: 40 },
  lesson_9: { id: 'lesson_9', name: 'Девять уроков', description: 'Пройди 9 уроков', icon: '🎈', points: 45 },
  lesson_11: { id: 'lesson_11', name: 'Одиннадцать уроков', description: 'Пройди 11 уроков', icon: '🥢', points: 55 },
  lesson_12: { id: 'lesson_12', name: 'Дюжина уроков', description: 'Пройди 12 уроков', icon: '🥚', points: 60 },
  lesson_13: { id: 'lesson_13', name: 'Тринадцать уроков', description: 'Пройди 13 уроков', icon: '🐈‍⬛', points: 65 },
  lesson_14: { id: 'lesson_14', name: 'Четырнадцать уроков', description: 'Пройди 14 уроков', icon: '🏰', points: 70 },
  lesson_16: { id: 'lesson_16', name: 'Шестнадцать уроков', description: 'Пройди 16 уроков', icon: '💾', points: 80 },
  lesson_17: { id: 'lesson_17', name: 'Семнадцать уроков', description: 'Пройди 17 уроков', icon: '🌟', points: 85 },
  lesson_18: { id: 'lesson_18', name: 'Восемнадцать уроков', description: 'Пройди 18 уроков', icon: '🚛', points: 90 },
  lesson_19: { id: 'lesson_19', name: 'Девятнадцать уроков', description: 'Пройди 19 уроков', icon: '🏌️', points: 95 },
  lesson_21: { id: 'lesson_21', name: 'Двадцать один', description: 'Пройди 21 урок', icon: '🃏', points: 105 },
  lesson_22: { id: 'lesson_22', name: 'Два гуся', description: 'Пройди 22 урока', icon: '🦆', points: 110 },
  lesson_23: { id: 'lesson_23', name: 'Двадцать три', description: 'Пройди 23 урока', icon: '🏀', points: 115 },
  lesson_24: { id: 'lesson_24', name: 'Сутки', description: 'Пройди 24 урока', icon: '🕛', points: 120 },

  // MICRO WORDS (19)
  words_5: { id: 'words_5', name: 'Пять слов', description: 'Изучи 5 слов', icon: '🖐️', points: 5 },
  words_15: { id: 'words_15', name: 'Пятнадцать слов', description: 'Изучи 15 слов', icon: '🗣️', points: 15 },
  words_20: { id: 'words_20', name: 'Двадцать слов', description: 'Изучи 20 слов', icon: '🦜', points: 20 },
  words_30: { id: 'words_30', name: 'Тридцать слов', description: 'Изучи 30 слов', icon: '📝', points: 30 },
  words_35: { id: 'words_35', name: 'Тридцать пять', description: 'Изучи 35 слов', icon: '📼', points: 35 },
  words_40: { id: 'words_40', name: 'Сорок слов', description: 'Изучи 40 слов', icon: '🧶', points: 40 },
  words_45: { id: 'words_45', name: 'Сорок пять', description: 'Изучи 45 слов', icon: '🫐', points: 45 },
  words_55: { id: 'words_55', name: 'Пятьдесят пять', description: 'Изучи 55 слов', icon: '🎼', points: 55 },
  words_60: { id: 'words_60', name: 'Шестьдесят слов', description: 'Изучи 60 слов', icon: '🐊', points: 60 },
  words_65: { id: 'words_65', name: 'Шестьдесят пять', description: 'Изучи 65 слов', icon: '👵', points: 65 },
  words_70: { id: 'words_70', name: 'Семьдесят слов', description: 'Изучи 70 слов', icon: '👴', points: 70 },
  words_80: { id: 'words_80', name: 'Восемьдесят слов', description: 'Изучи 80 слов', icon: '🎱', points: 80 },
  words_85: { id: 'words_85', name: 'Восемьдесят пять', description: 'Изучи 85 слов', icon: '🏎️', points: 85 },
  words_90: { id: 'words_90', name: 'Девяносто слов', description: 'Изучи 90 слов', icon: '📐', points: 90 },
  words_95: { id: 'words_95', name: 'Почти сотня', description: 'Изучи 95 слов', icon: '🤏', points: 95 },
  words_110: { id: 'words_110', name: 'Сто десять', description: 'Изучи 110 слов', icon: '🚑', points: 110 },
  words_120: { id: 'words_120', name: 'Сто двадцать', description: 'Изучи 120 слов', icon: '🚓', points: 120 },
  words_130: { id: 'words_130', name: 'Сто тридцать', description: 'Изучи 130 слов', icon: '🚒', points: 130 },
  words_140: { id: 'words_140', name: 'Сто сорок', description: 'Изучи 140 слов', icon: '🚜', points: 140 },

  // TIME SLOTS (8)
  night_owl_extreme: { id: 'night_owl_extreme', name: 'Полуночник', description: 'Пройди урок с 00:00 до 03:00', icon: '🌚', points: 30 },
  early_riser: { id: 'early_riser', name: 'Жаворонок', description: 'Пройди урок с 04:00 до 06:00', icon: '🐔', points: 30 },
  breakfast_club: { id: 'breakfast_club', name: 'За завтраком', description: 'Пройди урок с 08:00 до 10:00', icon: '🥞', points: 20 },
  late_morning: { id: 'late_morning', name: 'Второй завтрак', description: 'Пройди урок с 10:00 до 12:00', icon: '🥨', points: 20 },
  early_lunch: { id: 'early_lunch', name: 'Ранний обед', description: 'Пройди урок с 12:00 до 13:00', icon: '🥗', points: 20 },
  afternoon_tea: { id: 'afternoon_tea', name: 'Полдник', description: 'Пройди урок с 15:00 до 17:00', icon: '🍵', points: 20 },
  evening_relax: { id: 'evening_relax', name: 'Вечерний чил', description: 'Пройди урок с 19:00 до 21:00', icon: '🛋️', points: 20 },
  pre_sleep: { id: 'pre_sleep', name: 'Перед сном', description: 'Пройди урок с 21:00 до 23:00', icon: '🛌', points: 20 },

  // DAYS OF WEEK (5)
  tuesday_task: { id: 'tuesday_task', name: 'Вторник', description: 'Занимайся во вторник', icon: '📅', points: 30 },
  wednesday_hump: { id: 'wednesday_hump', name: 'Экватор', description: 'Занимайся в среду', icon: '🐫', points: 30 },
  thursday_thunder: { id: 'thursday_thunder', name: 'Четверг', description: 'Занимайся в четверг', icon: '⚡', points: 30 },
  saturday_chill: { id: 'saturday_chill', name: 'Суббота', description: 'Занимайся в субботу', icon: '🧘', points: 40 },
  sunday_funday: { id: 'sunday_funday', name: 'Воскресенье', description: 'Занимайся в воскресенье', icon: '⛪', points: 40 },

  // MILESTONES (12)
  lessons_33: { id: 'lessons_33', name: '33 Богатыря', description: 'Пройди 33 урока', icon: '🛡️', points: 150 },
  lessons_66: { id: 'lessons_66', name: 'Маршрут 66', description: 'Пройди 66 уроков', icon: '🛣️', points: 300 },
  lessons_99: { id: 'lessons_99', name: 'Почти сотня', description: 'Пройди 99 уроков', icon: '🎈', points: 400 },
  lessons_111: { id: 'lessons_111', name: 'Единички', description: 'Пройди 111 уроков', icon: '1️⃣', points: 500 },
  lessons_222: { id: 'lessons_222', name: 'Двойки', description: 'Пройди 222 урока', icon: '2️⃣', points: 1000 },
  lessons_333: { id: 'lessons_333', name: 'Тройки', description: 'Пройди 333 урока', icon: '3️⃣', points: 1500 },
  lessons_444: { id: 'lessons_444', name: 'Четверки', description: 'Пройди 444 урока', icon: '4️⃣', points: 2000 },
  lessons_555: { id: 'lessons_555', name: 'Пятерки', description: 'Пройди 555 уроков', icon: '5️⃣', points: 2500 },
  words_777: { id: 'words_777', name: 'Джекпот', description: 'Изучи 777 слов', icon: '🎰', points: 1000 },
  words_888: { id: 'words_888', name: 'Бесконечность', description: 'Изучи 888 слов', icon: '♾️', points: 1200 },
  words_1111: { id: 'words_1111', name: 'Час пик', description: 'Изучи 1111 слов', icon: '⌚', points: 1500 },
  words_1234: { id: 'words_1234', name: 'По порядку', description: 'Изучи 1234 слов', icon: '🔢', points: 1600 },

  // MORE XP (12)
  xp_50: { id: 'xp_50', name: 'Копилка', description: 'Набери 50 XP', icon: '🐖', points: 10 },
  xp_150: { id: 'xp_150', name: 'Горсть монет', description: 'Набери 150 XP', icon: '💰', points: 20 },
  xp_200: { id: 'xp_200', name: 'Мешочек', description: 'Набери 200 XP', icon: '👛', points: 30 },
  xp_300: { id: 'xp_300', name: 'Кошель', description: 'Набери 300 XP', icon: '👜', points: 40 },
  xp_400: { id: 'xp_400', name: 'Сундук', description: 'Набери 400 XP', icon: '📦', points: 50 },
  xp_600: { id: 'xp_600', name: 'Сейф', description: 'Набери 600 XP', icon: '🔐', points: 60 },
  xp_800: { id: 'xp_800', name: 'Банк', description: 'Набери 800 XP', icon: '🏦', points: 80 },
  xp_900: { id: 'xp_900', name: 'Хранилище', description: 'Набери 900 XP', icon: '🏢', points: 90 },
  xp_1200: { id: 'xp_1200', name: 'Сокровищница', description: 'Набери 1200 XP', icon: '🪙', points: 120 },
  xp_1400: { id: 'xp_1400', name: 'Золотая гора', description: 'Набери 1400 XP', icon: '⛰️', points: 140 },
  xp_1600: { id: 'xp_1600', name: 'Драконий клад', description: 'Набери 1600 XP', icon: '🐉', points: 160 },
  xp_1800: { id: 'xp_1800', name: 'Богатство', description: 'Набери 1800 XP', icon: '🤑', points: 180 },

  // MICRO PERFECTS (10)
  perfect_2: { id: 'perfect_2', name: 'Два в цель', description: 'Идеально пройди 2 урока', icon: '🎯', points: 25 },
  perfect_4: { id: 'perfect_4', name: 'Четыре в ряд', description: 'Идеально пройди 4 урока', icon: '🎳', points: 60 },
  perfect_6: { id: 'perfect_6', name: 'Шесть побед', description: 'Идеально пройди 6 уроков', icon: '🥇', points: 90 },
  perfect_7: { id: 'perfect_7', name: 'Семь чудес', description: 'Идеально пройди 7 уроков', icon: '🗽', points: 100 },
  perfect_8: { id: 'perfect_8', name: 'Восемь вершин', description: 'Идеально пройди 8 уроков', icon: '🏔️', points: 120 },
  perfect_9: { id: 'perfect_9', name: 'Девять жизней', description: 'Идеально пройди 9 уроков', icon: '🐈', points: 135 },
  perfect_11: { id: 'perfect_11', name: 'Одиннадцать звёзд', description: 'Идеально пройди 11 уроков', icon: '✨', points: 165 },
  perfect_12: { id: 'perfect_12', name: 'Дюжина побед', description: 'Идеально пройди 12 уроков', icon: '🌺', points: 180 },
  perfect_13: { id: 'perfect_13', name: 'Счастливое число', description: 'Идеально пройди 13 уроков', icon: '🍀', points: 195 },
  perfect_14: { id: 'perfect_14', name: 'Две недели побед', description: 'Идеально пройди 14 уроков', icon: '🗓️', points: 210 },

  // --- BATCH 4: THE COMPLETIONIST (129 New Achievements) ---

  // FILLING LESSON GAPS (50-100 range)
  lesson_26: { id: 'lesson_26', name: 'Двадцать шесть', description: 'Пройди 26 уроков', icon: '🅰️', points: 26 },
  lesson_27: { id: 'lesson_27', name: 'Двадцать семь', description: 'Пройди 27 уроков', icon: '🅱️', points: 27 },
  lesson_28: { id: 'lesson_28', name: 'Двадцать восемь', description: 'Пройди 28 уроков', icon: '🅾️', points: 28 },
  lesson_29: { id: 'lesson_29', name: 'Двадцать девять', description: 'Пройди 29 уроков', icon: '🆎', points: 29 },
  lesson_31: { id: 'lesson_31', name: 'Тридцать один', description: 'Пройди 31 урок', icon: '🕐', points: 31 },
  lesson_32: { id: 'lesson_32', name: 'Тридцать два', description: 'Пройди 32 урока', icon: '🕑', points: 32 },
  lesson_34: { id: 'lesson_34', name: 'Тридцать четыре', description: 'Пройди 34 урока', icon: '🕓', points: 34 },
  lesson_36: { id: 'lesson_36', name: 'Тридцать шесть', description: 'Пройди 36 уроков', icon: '🕕', points: 36 },
  lesson_37: { id: 'lesson_37', name: 'Тридцать семь', description: 'Пройди 37 уроков', icon: '🕖', points: 37 },
  lesson_38: { id: 'lesson_38', name: 'Тридцать восемь', description: 'Пройди 38 уроков', icon: '🕗', points: 38 },
  lesson_39: { id: 'lesson_39', name: 'Тридцать девять', description: 'Пройди 39 уроков', icon: '🕘', points: 39 },
  lesson_41: { id: 'lesson_41', name: 'Сорок один', description: 'Пройди 41 урок', icon: '🇮', points: 41 },
  lesson_42: { id: 'lesson_42', name: 'Смысл жизни', description: 'Пройди 42 урока', icon: '🌌', points: 42 },
  lesson_43: { id: 'lesson_43', name: 'Сорок три', description: 'Пройди 43 урока', icon: '🎣', points: 43 },
  lesson_44: { id: 'lesson_44', name: 'Сорок четыре', description: 'Пройди 44 урока', icon: '⛵', points: 44 },
  lesson_46: { id: 'lesson_46', name: 'Сорок шесть', description: 'Пройди 46 уроков', icon: '⚓', points: 46 },
  lesson_47: { id: 'lesson_47', name: 'Сорок семь', description: 'Пройди 47 уроков', icon: '🚀', points: 47 },
  lesson_48: { id: 'lesson_48', name: 'Сорок восемь', description: 'Пройди 48 уроков', icon: '🚁', points: 48 },
  lesson_49: { id: 'lesson_49', name: 'Сорок девять', description: 'Пройди 49 уроков', icon: '🚂', points: 49 },
  lesson_51: { id: 'lesson_51', name: 'Зона 51', description: 'Пройди 51 урок', icon: '👽', points: 51 },
  lesson_52: { id: 'lesson_52', name: 'Карточная колода', description: 'Пройди 52 урока', icon: '🃏', points: 52 },
  lesson_53: { id: 'lesson_53', name: 'Джокер', description: 'Пройди 53 урока', icon: '🤡', points: 53 },
  lesson_54: { id: 'lesson_54', name: 'Пятьдесят четыре', description: 'Пройди 54 урока', icon: '🅰️', points: 54 },
  lesson_55: { id: 'lesson_55', name: 'Две пятерки', description: 'Пройди 55 уроков', icon: '✋', points: 55 },
  lesson_56: { id: 'lesson_56', name: 'Пятьдесят шесть', description: 'Пройди 56 уроков', icon: '🅱️', points: 56 },
  lesson_57: { id: 'lesson_57', name: 'Пятьдесят семь', description: 'Пройди 57 уроков', icon: '🅾️', points: 57 },
  lesson_58: { id: 'lesson_58', name: 'Пятьдесят восемь', description: 'Пройди 58 уроков', icon: '🅿️', points: 58 },
  lesson_59: { id: 'lesson_59', name: 'Пятьдесят девять', description: 'Пройди 59 уроков', icon: '🆖', points: 59 },
  lesson_61: { id: 'lesson_61', name: 'Шестьдесят один', description: 'Пройди 61 урок', icon: '🆗', points: 61 },
  lesson_62: { id: 'lesson_62', name: 'Шестьдесят два', description: 'Пройди 62 урока', icon: '🆙', points: 62 },
  lesson_63: { id: 'lesson_63', name: 'Шестьдесят три', description: 'Пройди 63 урока', icon: '🆒', points: 63 },
  lesson_64: { id: 'lesson_64', name: 'Бит', description: 'Пройди 64 урока', icon: '👾', points: 64 },
  lesson_65: { id: 'lesson_65', name: 'Шестьдесят пять', description: 'Пройди 65 уроков', icon: '🥞', points: 65 },
  lesson_67: { id: 'lesson_67', name: 'Шестьдесят семь', description: 'Пройди 67 уроков', icon: '🆕', points: 67 },
  lesson_68: { id: 'lesson_68', name: 'Шестьдесят восемь', description: 'Пройди 68 уроков', icon: '🆓', points: 68 },
  lesson_69: { id: 'lesson_69', name: 'Nice', description: 'Пройди 69 уроков', icon: '♋', points: 69 },
  lesson_70: { id: 'lesson_70', name: 'Семьдесят', description: 'Пройди 70 уроков', icon: '🥖', points: 70 },
  lesson_88: { id: 'lesson_88', name: 'Две восьмерки', description: 'Пройди 88 уроков', icon: '🥨', points: 88 },
  lesson_95: { id: 'lesson_95', name: 'Девяносто пять', description: 'Пройди 95 уроков', icon: '🧀', points: 95 },
  lesson_128: { id: 'lesson_128', name: 'Байт', description: 'Пройди 128 уроков', icon: '💾', points: 128 },
  lesson_256: { id: 'lesson_256', name: 'Килобайт', description: 'Пройди 256 уроков', icon: '💿', points: 256 },

  // STREAK GAPS
  streak_3: { id: 'streak_3', name: 'Тройка', description: 'Занимайся 3 дня подряд', icon: '🥉', points: 15 },
  streak_7: { id: 'streak_7', name: 'Семерка', description: 'Занимайся 7 дней подряд', icon: '📅', points: 35 },
  streak_10: { id: 'streak_10', name: 'Десяточка', description: 'Занимайся 10 дней подряд', icon: '🔟', points: 50 },
  streak_22: { id: 'streak_22', name: 'Двадцать два', description: 'Занимайся 22 дня подряд', icon: '🦢', points: 110 },
  streak_23: { id: 'streak_23', name: 'Двадцать три', description: 'Занимайся 23 дня подряд', icon: '🏀', points: 115 },
  streak_24: { id: 'streak_24', name: 'Двадцать четыре', description: 'Занимайся 24 дня подряд', icon: '🕰️', points: 120 },
  streak_25: { id: 'streak_25', name: 'Четвертак', description: 'Занимайся 25 дней подряд', icon: '🪙', points: 125 },
  streak_26: { id: 'streak_26', name: 'Двадцать шесть', description: 'Занимайся 26 дней подряд', icon: '📼', points: 130 },
  streak_27: { id: 'streak_27', name: 'Двадцать семь', description: 'Занимайся 27 дней подряд', icon: '📺', points: 135 },
  streak_28: { id: 'streak_28', name: 'Двадцать восемь', description: 'Занимайся 28 дней подряд', icon: '📻', points: 140 },
  streak_29: { id: 'streak_29', name: 'Двадцать девять', description: 'Занимайся 29 дней подряд', icon: '🎙️', points: 145 },
  streak_35: { id: 'streak_35', name: '35 Дней', description: 'Занимайся 35 дней подряд', icon: '🗓️', points: 175 },
  streak_40: { id: 'streak_40', name: '40 Дней', description: 'Занимайся 40 дней подряд', icon: '📆', points: 200 },
  streak_50: { id: 'streak_50', name: 'Полтинник', description: 'Занимайся 50 дней подряд', icon: '🪙', points: 250 },
  streak_55: { id: 'streak_55', name: '55 Дней', description: 'Занимайся 55 дней подряд', icon: '💎', points: 275 },
  streak_65: { id: 'streak_65', name: '65 Дней', description: 'Занимайся 65 дней подряд', icon: '💍', points: 325 },
  streak_70: { id: 'streak_70', name: '70 Дней', description: 'Занимайся 70 дней подряд', icon: '👑', points: 350 },
  streak_80: { id: 'streak_80', name: '80 Дней', description: 'Занимайся 80 дней подряд', icon: '🧢', points: 400 },
  streak_85: { id: 'streak_85', name: '85 Дней', description: 'Занимайся 85 дней подряд', icon: '👒', points: 425 },
  streak_95: { id: 'streak_95', name: '95 Дней', description: 'Занимайся 95 дней подряд', icon: '🎩', points: 475 },

  // WORD GAPS
  words_101: { id: 'words_101', name: '101 Далматинец', description: 'Изучи 101 слово', icon: '🐶', points: 10 },
  words_111: { id: 'words_111', name: 'Барабанные палочки', description: 'Изучи 111 слов', icon: '🥁', points: 111 },
  words_125: { id: 'words_125', name: 'Восьмая часть', description: 'Изучи 125 слов', icon: '🍕', points: 125 },
  words_175: { id: 'words_175', name: 'Сто семьдесят пять', description: 'Изучи 175 слов', icon: '🌭', points: 175 },
  words_202: { id: 'words_202', name: '202 слова', description: 'Изучи 202 слова', icon: '🐩', points: 20 },
  words_222: { id: 'words_222', name: 'Уточки', description: 'Изучи 222 слова', icon: '🦆', points: 222 },
  words_225: { id: 'words_225', name: 'Двести двадцать пять', description: 'Изучи 225 слов', icon: '🧂', points: 225 },
  words_275: { id: 'words_275', name: 'Двести семьдесят пять', description: 'Изучи 275 слов', icon: '🍿', points: 275 },
  words_303: { id: 'words_303', name: '303 слова', description: 'Изучи 303 слова', icon: '🐕', points: 30 },
  words_333: { id: 'words_333', name: 'Триста тридцать три', description: 'Изучи 333 слова', icon: '🌫️', points: 333 },
  words_350: { id: 'words_350', name: 'Триста пятьдесят', description: 'Изучи 350 слов', icon: '🥫', points: 350 },
  words_404: { id: 'words_404', name: 'Слово не найдено', description: 'Изучи 404 слова', icon: '🚫', points: 40 },
  words_444: { id: 'words_444', name: 'Стульчики', description: 'Изучи 444 слова', icon: '🪑', points: 444 },
  words_450: { id: 'words_450', name: 'Четыреста пятьдесят', description: 'Изучи 450 слов', icon: '🥟', points: 450 },
  words_505: { id: 'words_505', name: '505 слов', description: 'Изучи 505 слов', icon: '🐺', points: 50 },
  words_555: { id: 'words_555', name: 'Три пятерки', description: 'Изучи 555 слов', icon: '📠', points: 555 },
  words_666: { id: 'words_666', name: 'Число зверя', description: 'Изучи 666 слов', icon: '😈', points: 666 },
  words_999: { id: 'words_999', name: 'Девятки', description: 'Изучи 999 слов', icon: '🙃', points: 999 },

  // XP MILESTONES
  xp_60: { id: 'xp_60', name: 'XP 60', description: 'Набери 60 XP', icon: '1️⃣', points: 12 },
  xp_70: { id: 'xp_70', name: 'XP 70', description: 'Набери 70 XP', icon: '2️⃣', points: 14 },
  xp_80: { id: 'xp_80', name: 'XP 80', description: 'Набери 80 XP', icon: '3️⃣', points: 16 },
  xp_90: { id: 'xp_90', name: 'XP 90', description: 'Набери 90 XP', icon: '4️⃣', points: 18 },
  xp_110: { id: 'xp_110', name: 'XP 110', description: 'Набери 110 XP', icon: '5️⃣', points: 22 },
  xp_120: { id: 'xp_120', name: 'XP 120', description: 'Набери 120 XP', icon: '6️⃣', points: 24 },
  xp_130: { id: 'xp_130', name: 'XP 130', description: 'Набери 130 XP', icon: '7️⃣', points: 26 },
  xp_140: { id: 'xp_140', name: 'XP 140', description: 'Набери 140 XP', icon: '8️⃣', points: 28 },
  xp_160: { id: 'xp_160', name: 'XP 160', description: 'Набери 160 XP', icon: '9️⃣', points: 32 },
  xp_170: { id: 'xp_170', name: 'XP 170', description: 'Набери 170 XP', icon: '🔟', points: 34 },
  xp_180: { id: 'xp_180', name: 'XP 180', description: 'Набери 180 XP', icon: '#️⃣', points: 36 },
  xp_190: { id: 'xp_190', name: 'XP 190', description: 'Набери 190 XP', icon: '*️⃣', points: 38 },
  xp_1100: { id: 'xp_1100', name: 'XP 1100', description: 'Набери 1100 XP', icon: '⚡', points: 55 },
  xp_1200_new: { id: 'xp_1200_new', name: 'XP 1200', description: 'Набери 1200 XP', icon: '🔥', points: 60 },
  xp_1300: { id: 'xp_1300', name: 'XP 1300', description: 'Набери 1300 XP', icon: '💧', points: 65 },
  xp_1400_new: { id: 'xp_1400_new', name: 'XP 1400', description: 'Набери 1400 XP', icon: '❄️', points: 70 },
  xp_1600_new: { id: 'xp_1600_new', name: 'XP 1600', description: 'Набери 1600 XP', icon: '🌪️', points: 80 },
  xp_1700: { id: 'xp_1700', name: 'XP 1700', description: 'Набери 1700 XP', icon: '🌫️', points: 85 },
  xp_1800_new: { id: 'xp_1800_new', name: 'XP 1800', description: 'Набери 1800 XP', icon: '🌈', points: 90 },
  xp_1900: { id: 'xp_1900', name: 'XP 1900', description: 'Набери 1900 XP', icon: '☀️', points: 95 },
  xp_2100: { id: 'xp_2100', name: 'XP 2100', description: 'Набери 2100 XP', icon: '🌘', points: 105 },
  xp_2200: { id: 'xp_2200', name: 'XP 2200', description: 'Набери 2200 XP', icon: '🌙', points: 110 },
  xp_2300: { id: 'xp_2300', name: 'XP 2300', description: 'Набери 2300 XP', icon: '🪐', points: 115 },
  xp_2400: { id: 'xp_2400', name: 'XP 2400', description: 'Набери 2400 XP', icon: '⭐', points: 120 },
  xp_2600: { id: 'xp_2600', name: 'XP 2600', description: 'Набери 2600 XP', icon: '🌟', points: 130 },
  xp_2700: { id: 'xp_2700', name: 'XP 2700', description: 'Набери 2700 XP', icon: '🌠', points: 135 },
  xp_2800: { id: 'xp_2800', name: 'XP 2800', description: 'Набери 2800 XP', icon: '🎇', points: 140 },
  xp_2900: { id: 'xp_2900', name: 'XP 2900', description: 'Набери 2900 XP', icon: '🎆', points: 145 },
  xp_3500: { id: 'xp_3500', name: 'XP 3500', description: 'Набери 3500 XP', icon: '🔋', points: 175 },
  xp_4500: { id: 'xp_4500', name: 'XP 4500', description: 'Набери 4500 XP', icon: '🔌', points: 225 },
  xp_5500: { id: 'xp_5500', name: 'XP 5500', description: 'Набери 5500 XP', icon: '💻', points: 275 },
  xp_6500: { id: 'xp_6500', name: 'XP 6500', description: 'Набери 6500 XP', icon: '🖥️', points: 325 },
  xp_8500: { id: 'xp_8500', name: 'XP 8500', description: 'Набери 8500 XP', icon: '🖨️', points: 425 },
  xp_9500: { id: 'xp_9500', name: 'XP 9500', description: 'Набери 9500 XP', icon: '🖱️', points: 475 },

  // PERFECT LESSONS
  perfect_16: { id: 'perfect_16', name: '16 Идеальных', description: 'Идеально пройди 16 уроков', icon: '💿', points: 215 },
  perfect_17: { id: 'perfect_17', name: '17 Идеальных', description: 'Идеально пройди 17 уроков', icon: '📀', points: 220 },
  perfect_18: { id: 'perfect_18', name: '18 Идеальных', description: 'Идеально пройди 18 уроков', icon: '📼', points: 225 },
  perfect_19: { id: 'perfect_19', name: '19 Идеальных', description: 'Идеально пройди 19 уроков', icon: '📷', points: 230 },
  perfect_20: { id: 'perfect_20', name: '20 Идеальных', description: 'Идеально пройди 20 уроков', icon: '📸', points: 235 },
  perfect_21: { id: 'perfect_21', name: '21 Идеальный', description: 'Идеально пройди 21 урок', icon: '📹', points: 240 },
  perfect_22: { id: 'perfect_22', name: '22 Идеальных', description: 'Идеально пройди 22 урока', icon: '🎥', points: 245 },
  perfect_23: { id: 'perfect_23', name: '23 Идеальных', description: 'Идеально пройди 23 урока', icon: '📽️', points: 250 },
  perfect_24: { id: 'perfect_24', name: '24 Идеальных', description: 'Идеально пройди 24 урока', icon: '🎞️', points: 255 },

  // COLLECTOR
  collector_1: { id: 'collector_1', name: 'Коллекционер I', description: 'Собери 10 наград', icon: '💼', points: 50 },
  collector_2: { id: 'collector_2', name: 'Коллекционер II', description: 'Собери 25 наград', icon: '👜', points: 100 },
  collector_3: { id: 'collector_3', name: 'Коллекционер III', description: 'Собери 50 наград', icon: '🎒', points: 200 },
  collector_4: { id: 'collector_4', name: 'Коллекционер IV', description: 'Собери 100 наград', icon: '👑', points: 400 },
  collector_5: { id: 'collector_5', name: 'Коллекционер V', description: 'Собери 200 наград', icon: '🏰', points: 800 },
  collector_6: { id: 'collector_6', name: 'Коллекционер VI', description: 'Собери 150 наград', icon: '🏛️', points: 600 },
  collector_7: { id: 'collector_7', name: 'Коллекционер VII', description: 'Собери 250 наград', icon: '🏟️', points: 1000 },

  // TIME
  siesta: { id: 'siesta', name: 'Сиеста', description: 'Занимайся с 14:00 до 16:00', icon: '🛌', points: 20 },
  sunset: { id: 'sunset', name: 'Закат', description: 'Занимайся с 19:00 до 20:00', icon: '🌇', points: 20 },
  midnight: { id: 'midnight', name: 'Полночь', description: 'Занимайся с 23:00 до 00:00', icon: '🕛', points: 30 },

  // --- SITUATIONS (50) ---
  sit_total_1: { id: 'sit_total_1', name: 'Первая ситуация', description: 'Успешно заверши свою первую ситуацию', icon: '🎭', points: 15 },
  sit_total_5: { id: 'sit_total_5', name: 'Практик', description: 'Заверши 5 ситуаций', icon: '🎬', points: 30 },
  sit_total_10: { id: 'sit_total_10', name: 'Актер', description: 'Заверши 10 ситуаций', icon: '🎭', points: 50 },
  sit_total_15: { id: 'sit_total_15', name: 'Мастер импровизации', description: 'Заверши 15 ситуаций', icon: '🎪', points: 75 },
  sit_total_20: { id: 'sit_total_20', name: 'Джентльмен удачи', description: 'Заверши 20 ситуаций', icon: '🎩', points: 100 },
  sit_total_25: { id: 'sit_total_25', name: 'Дипломат', description: 'Заверши 25 ситуаций', icon: '📜', points: 125 },
  sit_total_30: { id: 'sit_total_30', name: 'Человек мира', description: 'Заверши 30 ситуаций', icon: '🌍', points: 150 },
  sit_total_35: { id: 'sit_total_35', name: 'Местный житель', description: 'Заверши 35 ситуаций', icon: '🏠', points: 175 },
  sit_total_40: { id: 'sit_total_40', name: 'Знаток Финляндии', description: 'Заверши 40 ситуаций', icon: '🇫🇮', points: 200 },
  sit_total_45: { id: 'sit_total_45', name: 'Профи общения', description: 'Заверши 45 ситуаций', icon: '🗣️', points: 225 },
  sit_total_50: { id: 'sit_total_50', name: 'Свой в доску', description: 'Заверши 50 ситуаций', icon: '🤝', points: 300 },
  sit_total_60: { id: 'sit_total_60', name: 'Легенда ситуаций', description: 'Заверши 60 ситуаций', icon: '🏆', points: 400 },
  sit_total_70: { id: 'sit_total_70', name: 'Мастер диалога', description: 'Заверши 70 ситуаций', icon: '🗨️', points: 500 },
  sit_total_80: { id: 'sit_total_80', name: 'Гуру ролевой игры', description: 'Заверши 80 ситуаций', icon: '🎲', points: 600 },
  sit_total_90: { id: 'sit_total_90', name: 'Неудержимый', description: 'Заверши 90 ситуаций', icon: '⚡', points: 750 },
  sit_total_100: { id: 'sit_total_100', name: 'Владыка ситуаций', description: 'Заверши 100 ситуаций', icon: '👑', points: 1000 },

  sit_variety_1: { id: 'sit_variety_1', name: 'Разносторонний', description: 'Пройди 3 разные ситуации', icon: '🌈', points: 50 },
  sit_variety_5: { id: 'sit_variety_5', name: 'Исследователь', description: 'Пройди 5 разных ситуаций', icon: '🧭', points: 100 },
  sit_variety_10: { id: 'sit_variety_10', name: 'Первооткрыватель', description: 'Пройди 10 разных ситуаций', icon: '🗺️', points: 200 },
  sit_variety_15: { id: 'sit_variety_15', name: 'Жизненный опыт', description: 'Пройди 15 разных ситуаций', icon: '🎫', points: 300 },
  sit_variety_20: { id: 'sit_variety_20', name: 'Человек-оркестр', description: 'Пройди 20 разных ситуаций', icon: '🎷', points: 400 },
  sit_variety_25: { id: 'sit_variety_25', name: 'Мастер жизни', description: 'Пройди 25 разных ситуаций', icon: '🗝️', points: 500 },
  sit_variety_30: { id: 'sit_variety_30', name: 'Легенда улиц', description: 'Пройди 30 разных ситуаций', icon: '🌇', points: 1000 },

  sit_morning: { id: 'sit_morning', name: 'Утренняя репетиция', description: 'Пройди ситуацию до 10 утра', icon: '☕', points: 20 },
  sit_night: { id: 'sit_night', name: 'Ночная сцена', description: 'Пройди ситуацию после 22:00', icon: '🌙', points: 20 },
  sit_marathon: { id: 'sit_marathon', name: 'Актерский марафон', description: 'Пройди 3 ситуации за один день', icon: '🏃‍♂️', points: 50 },
  sit_fast: { id: 'sit_fast', name: 'Быстро сообразил', description: 'Пройди ситуацию без ошибок', icon: '⚡', points: 100 },
  sit_points_100: { id: 'sit_points_100', name: 'Блестящая игра', description: 'Набери 100 XP на ситуациях', icon: '✨', points: 50 },
  sit_points_500: { id: 'sit_points_500', name: 'Звезда ситуаций', description: 'Набери 500 XP на ситуациях', icon: '🌟', points: 200 },
  sit_points_1000: { id: 'sit_points_1000', name: 'Король драмы', description: 'Набери 1000 XP на ситуациях', icon: '💎', points: 500 },

  sit_persistent: { id: 'sit_persistent', name: 'Настойчивый юзер', description: 'Заверши ситуацию, потратив более 5 минут', icon: '⏳', points: 40 },
  sit_streak_2: { id: 'sit_streak_2', name: 'Стабильность', description: 'Проходи ситуации 2 дня подряд', icon: '🔥', points: 50 },
  sit_streak_7: { id: 'sit_streak_7', name: 'Неделя ситуаций', description: 'Проходи ситуации 7 дней подряд', icon: '📅', points: 200 },

  // --- RANDOM WORDS (50) ---
  ...Object.fromEntries(Array.from({ length: 50 }, (_, i) => [
    `rnd_total_${i + 1}`,
    { id: `rnd_total_${i + 1}`, name: `Рандом: Уровень ${i + 1}`, description: `Пройди ${i + 1} уроков в случайном режиме`, icon: '🎲', points: 10 + i }
  ])),

  // --- INTENSIVE TRAINING (50) ---
  ...Object.fromEntries(Array.from({ length: 50 }, (_, i) => [
    `int_total_${i + 1}`,
    { id: `int_total_${i + 1}`, name: `Интенсив: Ранг ${i + 1}`, description: `Пройди ${i + 1} интенсивных тренировок`, icon: '🔥', points: 20 + i }
  ])),
}
